title: Ibrahim Rondon
logo: /assets/img/profile.png
description: ğŸ“Loja, Ecuador
[![VideoCV](https://img.youtube.com/vi/AR3eefRA1IE/0.jpg)](https://www.youtube.com/watch?v=AR3eefRA1IE)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
